steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-west4-docker.pkg.dev/tienda-microservices-430113/image-registry/products-ms",
        "-f",
        "Dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west4-docker.pkg.dev/tienda-microservices-430113/image-registry/products-ms",
      ]
options:
  logging: CLOUD_LOGGING_ONLY

